# Generated by Django 4.2.3 on 2025-03-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_employer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="is_true_attender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employer",
            name="stage",
            field=models.IntegerField(default=0),
        ),
    ]
