# Generated by Django 4.2.3 on 2025-03-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_employer", "0002_employer_is_true_attender_employer_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="introduction_summary",
            field=models.TextField(null=True),
        ),
    ]
